### ISSUE TITLE
UI hairlines are all different colors:

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2000]
In the image below, I see 5 beige hairlines that are three different colors:

* #51504c (transform panel)
* #6a6965 (layers panel)
* #787772 (second of three in the libraries panel)

![image](https://cloud.githubusercontent.com/assets/1075154/9213685/266a6764-404a-11e5-8536-29819a4cc19c.png)

This aggression will not stand!

**Comment by placegraphichere** [comment]
It should be #3f3f3f for underlines and hairlines.

**Comment by chadrolfs** [comment]
Fixed by #2115?

**Comment by iwehrman** [comment]
Yes, fix in progress.

**Comment by placegraphichere** [comment]
this is not addressed by #2115 so we can continue to track it

**Comment by DivyaPrabhakar** [comment]
I'll fix it in that case

**Comment by iwehrman** [comment]
@DivyaPrabhakar I suggest waiting for #2115 to land, or just contributing a fix to @placegraphichere's branch if you want to look into it sooner.

**Comment by DivyaPrabhakar** [comment]
@iwehrman @placegraphichere In line with #2108, we are moving away from hairlines and I just pulled the most recent version of master and all the hairlines @iwehrman is referencing have been removed already. The last one, the libraries panel, is also getting removed once #2151 gets merged. Back to you Ian to close because I think this bug been taken care of now.

**Comment by iwehrman** [comment]
@DivyaPrabhakar The usual flow of things is that issues should be assigned back to the original filer once they're fixed in master. But this isn't fixed in master yet, since #2151 hasn't been merged yet.

**Comment by iwehrman** [comment]
Now the problem is that the hairlines are inconsistent across datalists. In the Type panel, there are no hairlines until you hover. In CC Libraries, there is always a hairline, and it's a different color from the one in the type panel. Also there is a different amount of horizontal space between the hairline and the menu in the components. Also, the type seems smaller in CC Libraries, but that could just be an illusion. So, back to @DivyaPrabhakar for additional tweaks.

![image](https://cloud.githubusercontent.com/assets/1075154/9531462/df3ab22c-4cba-11e5-8a5e-44342171c6bb.png)

**Comment by iwehrman** [comment]
Fixed by something or other.
