### ISSUE TITLE
Artboard add UI shows both standard and DS add UI; gets stuck in standard PS tools

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2836]
new doc,
drag a CC Library graphic asset onto canvas 
click on AB title

Result: 
![ab-doubleui](https://cloud.githubusercontent.com/assets/8442631/10324692/72f48980-6c40-11e5-9223-bdfd2d0161ee.png)

**Comment by iwehrman** [comment]
@chadrolfs Please file a high-priority core bug for this and assign to CJB.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4069723

**Comment by chadrolfs** [comment]
Worse than I thought: 
new doc,
drag a CC Library graphic asset onto canvas, Enter to place
hit r key for Rect tool

Result: you get standard PS rotation tool.  if you hit Q, you go into quick mask mode.

**Comment by shaoshing** [comment]
I've updated how we restore policies for placing graphic asset in PR 2837. However this issue is not entirely fiexd becaue we are not receiving the "placeEvent" from Photoshop (729), so the new layer is not added to DS.

**Comment by iwehrman** [comment]
@shaoshing is a new Watson bug needed for the missing `placeEvent`?

**Comment by shaoshing** [comment]
@iwehrman Jesper updated the watson bug saying the `placeEvent` needs to be disabled for graphic asset for now due to 

```
	// Until This code knows how to record and playback a place that references
	// a library elementRef, just disable recording for library places. Otherwise
	// they would record with references to the file in the libs cache folder
	// which is no good, especially in the case of a linked place (you'd end up
	// with a local link to the cache folder file on playback).
```

I think I will hook up the addLayer to the `toolModalStateChange` event and that should fix the problem. working on a fix now.

**Comment by shaoshing** [comment]
I am pausing my work on this until Jesper and Tai figure out whether or not Photoshop should emit the `placeEvent` for placing graphic from libraries.

**Comment by shaoshing** [comment]
Jesper's work in dev.739 fixes the issue perfectly. @chadrolfs can you verify?

**Comment by chadrolfs** [comment]
Getting access or stuck with standard PS tools looks fixed but I'm still seeing the standard PS AB UI on windows with dev.721 and master @ 3bc3356

**Comment by chadrolfs** [comment]
hmmmm, maybe it is fixed, having a hard time repro'ing now.

**Comment by chadrolfs** [comment]
definitely harder to repro now.  might be a timing thing but here it is:
![2ui](https://cloud.githubusercontent.com/assets/8442631/10382853/444c9778-6ddd-11e5-9fa2-962c821c4b7f.png)

**Comment by shaoshing** [comment]
The current win build failed to initialize event policy and seems unrelated to graphic drag-n-drop. You cannot even switch tools using the shortcut, or hover / click on layer. Chad mentioned some core issues so I assigned this back to him to verify. Please assign back to me if it can still be reproduced.

**Comment by chadrolfs** [comment]
Removing FIX NOW.  Hard to repro.  Only seen currently on Win with devtools.  If CNR without devtools, I will close this.

**Comment by chadrolfs** [comment]
Bounced watson.  Could repro without dev tools. comments in the watson bug

**Comment by chadrolfs** [comment]
Just repro'd on MBP Retina with pgdev.765, while trying to repro #2720 

<img width="1440" alt="screen shot 2015-10-13 at 9 45 35 am" src="https://cloud.githubusercontent.com/assets/8442631/10461883/5925df36-7190-11e5-841d-b9d363d47b8c.png">

**Comment by tiburbage** [comment]
Tested with pgdev.774 (Mac) and pgdev.754 (Win): all better now. Added in testing of similar "overlapping policy regions" scenario with a shape selected. No issues detected.
